config {
    type: "table",
    description: "Cleaned up data corresponding to CA one-year graduation rates"
}

select 
    academic_year,
    concat(lpad(county_code,2),lpad(district_code,5),lpad(school_code,7)) as cds_code,
    county_name,
    district_name,
    school_name,
    reporting_category,
    cast(one_year_graduate_count as INT64) as one_yr_grad_count
from ${ref("ca_doe_1_yr_graduation_rate")}
where aggregate_level = 'C'
limit 10

